---
include:
  - local: '.gitlab-ci-pages.yml'
  - local: '.gitlab-ci-slides.yml'

python:
  image: debian:bullseye
  script:
    - apt-get update
    - apt-get install -y git
    - git submodule update --init --recursive
    - scripts/provision-packaging-python
    - mkdir -p dist
    - make build-python-package
  artifacts:
    paths:
      - dist
  only:
    - main

debian:
  image: debian:bullseye
  script:
    - apt-get update
    - apt-get install -y git
    - git submodule update --init --recursive
    - scripts/provision-packaging-debian
    - make build-debian-test-package
    - mkdir -p dist
    - mv ../onionprobe_* dist
  artifacts:
    paths:
      - dist
  only:
    - main

configs:
  image: debian:bullseye
  script:
    - apt-get update
    - apt-get install -y git
    - git submodule update --init --recursive
    - scripts/provision-onionprobe
    - make configs
  artifacts:
    paths:
      - configs
  only:
    - main
