pages:
  image: debian:bookworm
  script:
    - apt-get update
    - apt-get install -y git
    - git submodule update --init --recursive
    - vendors/onion-mkdocs/scripts/onion-mkdocs-provision-build
    - scripts/provision-onionprobe
    - make docs
  artifacts:
    paths:
      - public
  #only:
  #  - main
