pages:
  image: debian:bullseye
  script:
    - apt-get update
    - apt-get install -y git
    - git submodule update --init --recursive
    - vendors/onion-mkdocs/scripts/provision-docs-build
    - make compile-docs
  artifacts:
    paths:
      - public
  only:
    - main
