---
version: '3'

services:
  prometheus:
    image: docker.io/prom/prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  # This service currently is shipper with a hardcoded HashedControlPassword,
  # so please use it only fort testing purposes and not in production
  #tor:
  #  image: "rhatto/tor:1.0"
  #  build:
  #    context: .
  #    dockerfile: containers/tor/Dockerfile
  #  restart: always
  #  #ports:
  #  #  - 9050:9050
  #  #  - 9051:9051

  onionprobe:
    image: "rhatto/onionprobe:1.0"
    build:
      context: .
      dockerfile: containers/onionprobe/Dockerfile
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - .:/srv/onionprobe
    #depends_on:
    #  - tor
