---
# Sample Prometheus test rule file to be used with Docker Compose.
#
# Copyright (C) 2025 The Tor Project, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

rule_files:
  - prometheus-rules.yml

tests:
  # General reachability tests
  - interval: 1m
    input_series:
      - series: 'onion_service_reachable{address="testn5cs76tk2hk3mwoqkugkwwcljp4c6gpzoclwou7mmobiqabn5wid.onion", alertname="Onion Service unreachable", instance="onionprobe:9935", job="onionprobe", name="Test", path="/", port="443", protocol="https", severity="critical"}'
        values: 0x30
    alert_rule_test:
      - eval_time: 10m
        alertname: Onion Service unreachable
        exp_alerts: []
      - eval_time: 30m
        alertname: Onion Service unreachable
        exp_alerts:
          - exp_labels:
              severity  : critical
              address   : testn5cs76tk2hk3mwoqkugkwwcljp4c6gpzoclwou7mmobiqabn5wid.onion
              alertname : "Onion Service descriptor unreachable"
              instance  : onionprobe:9935
              job       : onionprobe
              name      : Test
              path      : /
              port      : 443
              protocol  : https
            exp_annotations:
              summary: >
                Onion Service unreachable:
                testn5cs76tk2hk3mwoqkugkwwcljp4c6gpzoclwou7mmobiqabn5wid.onion
              description: >
                Onionprobe was unable to connect to the Onion Service:
                testn5cs76tk2hk3mwoqkugkwwcljp4c6gpzoclwou7mmobiqabn5wid.onion
              playbook: 'https://onionservices.torproject.org/apps/web/onionprobe/troubleshooting/#onion-service-unreachable'

  # Descriptor reachability tests
  - interval: 1m
    input_series:
      - series: 'onion_service_descriptor_reachable{address="testn5cs76tk2hk3mwoqkugkwwcljp4c6gpzoclwou7mmobiqabn5wid.onion", alertname="Onion Service descriptor unreachable", instance="onionprobe:9935", job="onionprobe", name="Test", severity="critical"}'
        values: 0x30
    alert_rule_test:
      - eval_time: 10m
        alertname: Onion Service descriptor unreachable
        exp_alerts: []
      - eval_time: 30m
        alertname: Onion Service descriptor unreachable
        exp_alerts:
          - exp_labels:
              severity  : critical
              address   : testn5cs76tk2hk3mwoqkugkwwcljp4c6gpzoclwou7mmobiqabn5wid.onion
              alertname : "Onion Service descriptor unreachable"
              instance  : onionprobe:9935
              job       : onionprobe
              name      : Test
            exp_annotations:
              summary: >
                Onion Service descriptor unreachable:
                testn5cs76tk2hk3mwoqkugkwwcljp4c6gpzoclwou7mmobiqabn5wid.onion
              description: >
                The Onion Service descriptor for
                testn5cs76tk2hk3mwoqkugkwwcljp4c6gpzoclwou7mmobiqabn5wid.onion
                has become unreachable from Onionprobe.
              playbook: 'https://onionservices.torproject.org/apps/web/onionprobe/troubleshooting/#onion-service-descriptor-unreachable'

  # Invalid certificate tests
  - interval: 1m
    input_series:
      - series: 'onion_service_valid_certificate{address="testn5cs76tk2hk3mwoqkugkwwcljp4c6gpzoclwou7mmobiqabn5wid.onion", alertname="Invalid certificate for the Onion Service", instance="onionprobe:9935", job="onionprobe", name="Test", path="/", port="443", protocol="https", severity="critical"}'
        values: 0x30
    alert_rule_test:
      - eval_time: 30m
        alertname: Invalid TLS certificate for the Onion Service
        exp_alerts:
          - exp_labels:
              severity  : critical
              address   : testn5cs76tk2hk3mwoqkugkwwcljp4c6gpzoclwou7mmobiqabn5wid.onion
              alertname : "Invalid TLS certificate for the Onion Service"
              instance  : onionprobe:9935
              job       : onionprobe
              name      : Test
              path      : /
              port      : 443
              protocol  : https
            exp_annotations:
              summary: >
                Invalid TLS certificate for the Onion Service:
                testn5cs76tk2hk3mwoqkugkwwcljp4c6gpzoclwou7mmobiqabn5wid.onion
              description: >
                The TLS certificate for the Onion Service
                testn5cs76tk2hk3mwoqkugkwwcljp4c6gpzoclwou7mmobiqabn5wid.onion
                is invalid
              playbook: 'https://onionservices.torproject.org/apps/web/onionprobe/troubleshooting/#invalid-tls-certificate-for-the-onion-service'

  # Certificate expiration tests
  - interval: 1m
    input_series:
      - series: 'onion_service_certificate_expiry_seconds{address="testn5cs76tk2hk3mwoqkugkwwcljp4c6gpzoclwou7mmobiqabn5wid.onion", alertname="Expiring certificate for the Onion Service", instance="onionprobe:9935", job="onionprobe", name="Test", port="443", severity="page"}'
        # Series: (86400 * 7)  +  (60 * 10), decrementing 60 seconds every minute, 30 times
        #          a week         ten minutes
        #
        # Series starts with the value for a certificate expiring in one week plus ten minutes.
        # The alert should fire in eleven minutes.
        values: 605400-60x30
    alert_rule_test:
      - eval_time: 10m
        alertname: Expiring TLS certificate for the Onion Service
        exp_alerts: []
      - eval_time: 11m
        alertname: Expiring TLS certificate for the Onion Service
        exp_alerts:
          - exp_labels:
              severity  : page
              address   : testn5cs76tk2hk3mwoqkugkwwcljp4c6gpzoclwou7mmobiqabn5wid.onion
              alertname : Expiring TLS certificate for the Onion Service
              instance  : onionprobe:9935
              job       : onionprobe
              name      : Test
              port      : 443
            exp_annotations:
              summary: >
                Expiring TLS certificate for the Onion Service:
                testn5cs76tk2hk3mwoqkugkwwcljp4c6gpzoclwou7mmobiqabn5wid.onion
              description: >
                The TLS certificate for the Onion Service
                testn5cs76tk2hk3mwoqkugkwwcljp4c6gpzoclwou7mmobiqabn5wid.onion
                will expie in less than a week.
              playbook: 'https://onionservices.torproject.org/apps/web/onionprobe/troubleshooting/#expiring-tls-certificate-for-the-onion-service'

  # Status code tests
  - interval: 1m
    input_series:
      - series: 'onion_service_unexpected_status_code{address="testn5cs76tk2hk3mwoqkugkwwcljp4c6gpzoclwou7mmobiqabn5wid.onion", alertname="Status code", instance="onionprobe:9935", job="onionprobe", name="Test", path="/", port="443", protocol="https", severity="critical"}'
        values: 1x250
    alert_rule_test:
      - eval_time: 10m
        alertname: Unexpected HTTP status code
        exp_alerts: []
      - eval_time: 30m
        alertname: Unexpected HTTP status code
        exp_alerts:
          - exp_labels:
              severity  : critical
              address   : testn5cs76tk2hk3mwoqkugkwwcljp4c6gpzoclwou7mmobiqabn5wid.onion
              alertname : "Unexpected HTTP status code"
              instance  : onionprobe:9935
              job       : onionprobe
              name      : Test
              path      : /
              port      : 443
              protocol  : https
            exp_annotations:
              summary: >
                Unexpected HTTP status code for Onion Service:
                testn5cs76tk2hk3mwoqkugkwwcljp4c6gpzoclwou7mmobiqabn5wid.onion
              description: >
                Onionprobe got an unexpected HTTP status code when trying to
                connect to testn5cs76tk2hk3mwoqkugkwwcljp4c6gpzoclwou7mmobiqabn5wid.onion
              playbook: 'https://onionservices.torproject.org/apps/web/onionprobe/troubleshooting/#unexpected-http-status-code'
