control_port: 19051
endpoints:
  treacherous.tech:
    address: ygwdnjw2gt6sabcrhjqmpgsn4hhddomhipdpxbx6bru2zr2damxevqyd.onion
    paths:
    - path: /
    port: 443
    protocol: https
interval: 5
launch_tor: true
log_level: info
loop: true
new_circuit: false
prometheus_exporter: true
prometheus_exporter_port: 9091
randomize: true
shuffle: true
sleep: 5
socks_port: 19050
tor_address: 127.0.0.1
