#!/usr/bin/env bash
#
# Helper script to setup a Debian packaging environment
#

# Parameters
DIRNAME="`dirname $0`"
BASEPATH="$DIRNAME/.."
DEPENDENCIES_PACKAGING_DEBIAN="sbuild-debian-developer-setup piuparts"

# Debian packaging
sudo apt-get update
sudo apt-get install -y $DEPENDENCIES_PACKAGING_DEBIAN

# Sbuild chroot for unstable
if [ ! -e "/srv/chroot/unstable-amd64-sbuild" ]; then
  #sudo sbuild-debian-developer-setup --distribution=unstable
  sudo sbuild-createchroot  --include=eatmydata,gnupg unstable /srv/chroot/unstable-amd64-sbuild http://deb.debian.org/debian
fi

# Sbuild chroot for stable
#if [ ! -e "/srv/chroot/stable-amd64-sbuild" ]; then
#  sudo sbuild-createchroot --include=eatmydata,gnupg stable   /srv/chroot/stable-amd64-sbuild   http://deb.debian.org/debian
#  sudo sbuild-debian-developer-setup --distribution=stable
#fi

sudo sbuild-adduser $LOGNAME

if [ ! -e "$HOME/.sbuildrc" ]; then
  cp /usr/share/doc/sbuild/examples/example.sbuildrc $HOME/.sbuildrc
fi

# This allows one to build Debian packages inside a KVMX virtual machine
#if [ -d "/srv/onionprobe" ]; then
#  sudo chown user. /srv/onionprobe
#fi
