#!/usr/bin/env bash
#
# Helper script to setuo a development environment
#

# Parameters
DIRNAME="`dirname $0`"
BASEPATH="$DIRNAME/.."
DEPENDENCIES="python3-prometheus-client python3-stem python3-cryptography python3-yaml python3-requests python3-socks"
#DEPENDENCIES="python3-bs4 python3-pytest"
DEPENDENCIES="$DEPENDENCIES tor"
DEPENDENCIES_DOCS="pandoc latexmk texlive-latex-extra texlive-fonts-extra"
TORRC="/etc/tor/torrc"

# Install dependencies
sudo apt install -y $DEPENDENCIES

# Configure Tor
if ! grep "^ControlPort" $TORRC; then

  control_pass="$(grep "^control_password" $BASEPATH/onionprobe.yaml | cut -d "'" -f 2)"
  hashed_pass="`tor --hash-password $control_pass`"

  echo "SocksPort   19050"                  | sudo tee -a $TORRC > /dev/null
  echo "ControlPort 19051"                  | sudo tee -a $TORRC > /dev/null
  echo "HashedControlPassword $hashed_pass" | sudo tee -a $TORRC > /dev/null

  sudo service tor restart
fi

# Docker and docker-compose from distribution
sudo apt-get install -y docker.io docker-compose

# Put the regular user into docker group
sudo usermod -a -G docker $(whoami)

# Docs
# Not automatically installed because some texlive packages uses a lot of diskspace
#sudo apt-get install -y $DEPENDENCIES_DOCS
