#!/usr/bin/env bash
#
# Helper script to setup a development environment
#

# Parameters
DIRNAME="`dirname $0`"
BASEPATH="$DIRNAME/.."
TORRC="/etc/tor/torrc"

# Update submodules
git submodule update --init --recursive

# Provision Onionprobe requirements
$DIRNAME/provision-onionprobe

# Configure Tor
# This is mainly intended to test Onionprobe using a system-wide Tor daemon,
# i.e., when not using the built-in Tor process handling.
if ! grep "^ControlPort" $TORRC; then

  control_pass="$(grep "^control_password" $BASEPATH/onionprobe.yaml | cut -d "'" -f 2)"
  hashed_pass="`tor --hash-password $control_pass`"

  echo "SocksPort   19050"                  | sudo tee -a $TORRC > /dev/null
  echo "ControlPort 19051"                  | sudo tee -a $TORRC > /dev/null
  echo "HashedControlPassword $hashed_pass" | sudo tee -a $TORRC > /dev/null

  sudo service tor restart
fi

# Docker and docker-compose from distribution
sudo apt-get update
sudo apt-get install -y docker.io docker-compose

# Put the regular user into docker group
sudo usermod -a -G docker $(whoami)

# Provision documentation requirements
$BASEPATH/vendors/onion-mkdocs/scripts/provision-docs-build
$BASEPATH/vendors/onion-tex-slim/scripts/provision-docs-build

# Provision Python packaging requirements
$DIRNAME/provision-packaging-python

# Provision Debian packaging requirements
$DIRNAME/provision-packaging-debian
