{
 "title": "Onion Services",
 "description": "Onion Services status",
 "tags": [
  "tor",
  "onion services"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Onion Services Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Failure rate",
   "type": "gauge",
   "description": "General failure rate, relative to the total monitored onionsites",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(onion_service_reachable == 0)/count(onion_service_probe_status_info)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total services",
   "type": "stat",
   "description": "The total number of onionsites already tested in the current Onionprobe run",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(onion_service_probe_status_info) or vector(0)"
    }
   ]
  },
  {
   "title": "Offline instances",
   "type": "stat",
   "description": "Unreachable onionsite instances (either the descriptor is not available or the service seems offline)",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(onion_service_reachable == 0) or vector(0)"
    }
   ]
  },
  {
   "title": "Invalid certs",
   "type": "stat",
   "description": "Invalid TLS certificates",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(onion_service_valid_certificate == 0) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TLS certificate expirations",
   "type": "table",
   "description": "Expiring or already expired TLS certificates, up to 180 days ahead",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "sort(onion_service_certificate_not_valid_after_timestamp_seconds < time() + (86400 * 180))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP errors",
   "type": "stat",
   "description": "Unexpected HTTP status codes",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(onion_service_unexpected_status_code == 1) or vector(0)"
    }
   ]
  },
  {
   "title": "Missing descriptors",
   "type": "stat",
   "description": "Unreachable descriptors",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(onion_service_descriptor_reachable == 0) or vector(0)"
    }
   ]
  },
  {
   "title": "Expiring certs",
   "type": "stat",
   "description": "TLS certificates expiring in the next 7 days",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(onion_service_certificate_expiry_seconds < 86400 * 7) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unreachable instances",
   "type": "timeseries",
   "description": "Total number of unreachable instances (either missing descriptor or service offline)",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "count(onion_service_reachable != 1) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unreachable instances",
   "type": "table",
   "description": "List of unreachable instances (either missing descriptor or service offline)",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 11 },
   "targets": [
    { "expr": "onion_service_reachable != 1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Invalid certs",
   "type": "table",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "onion_service_valid_certificate == 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP errors",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 19 },
   "targets": [
    {
     "expr": "onion_service_unexpected_status_code == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Min. service latency",
   "type": "stat",
   "description": "Minimal Onion Service latency in seconds. Each onionsite is averaged over 30 minutes.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(onion_service_latency_seconds[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min. desc. latency",
   "type": "stat",
   "description": "Minimal Onionsite descriptor latency in seconds. Each onionsite is averaged over 30 minutes.",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(min_over_time(onion_service_descriptor_latency_seconds[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Onion Services latency",
   "type": "timeseries",
   "description": "Onion Services latency in seconds. Each onionsite is averaged over 30 minutes.",
   "gridPos": { "h": 18, "w": 9, "x": 6, "y": 26 },
   "targets": [
    {
     "expr": "min(avg_over_time(onion_service_latency_seconds[30m]))",
     "legendFormat": "Minimum latency"
    },
    {
     "expr": "avg(avg_over_time(onion_service_latency_seconds[30m]))",
     "legendFormat": "Average latency"
    },
    {
     "expr": "max(avg_over_time(onion_service_latency_seconds[30m]))",
     "legendFormat": "Maximum latency"
    }
   ]
  },
  {
   "title": "Onion Services Descriptor latency",
   "type": "timeseries",
   "description": "Average Onion Services Descriptor latency in seconds. Each onionsite is averaged over 30 minutes.",
   "gridPos": { "h": 18, "w": 9, "x": 15, "y": 26 },
   "targets": [
    {
     "expr": "min(avg_over_time(onion_service_descriptor_latency_seconds[30m]))",
     "legendFormat": "Minimum desc. latency"
    },
    {
     "expr": "avg(avg_over_time(onion_service_descriptor_latency_seconds[30m]))",
     "legendFormat": "Average desc. latency"
    },
    {
     "expr": "max(avg_over_time(onion_service_descriptor_latency_seconds[30m]))",
     "legendFormat": "Maximum desc. latency"
    }
   ]
  },
  {
   "title": "Avg. service latency",
   "type": "stat",
   "description": "Average Onion Services latency. Each onionsite is averaged over 30 minutes.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(onion_service_latency_seconds[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. desc. latency",
   "type": "stat",
   "description": "Average descriptor latency in seconds from all onionsites. Each onionsite is averaged over 30 minutes.",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(onion_service_descriptor_latency_seconds[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "High. service latency",
   "type": "stat",
   "description": "Highest Onion Services latency. Each onionsite is averaged over 30 minutes.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(onion_service_latency_seconds[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "High. desc. latency",
   "type": "stat",
   "description": "Highest descriptor fetch latency found in all onionsites, based on 30m averages",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(onion_service_descriptor_latency_seconds[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Single Onion Services",
   "type": "gauge",
   "description": "Percentage of Onion Services using the single circuit hop mode, from the total probed",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(onion_service_is_single==1)/count(onion_service_is_single)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow onionsites",
   "type": "table",
   "description": "Onionsites with latency over 20 seconds.",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 44 },
   "targets": [
    {
     "expr": "sort_desc(avg_over_time(onion_service_latency_seconds[30m]) > 20)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Descriptors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Missing descriptors",
   "type": "table",
   "description": "List of missing descriptors in the HSDirs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "onion_service_descriptor_info{state!=\"RECEIVED\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outer wrapper",
   "type": "timeseries",
   "description": "Minimum, average an maximum outer wrapper descriptor size in bytes (decrypted)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "min(onion_service_descriptor_outer_wrapper_size_bytes) or vector(0)",
     "legendFormat": "Minimum size"
    },
    {
     "expr": "avg(onion_service_descriptor_outer_wrapper_size_bytes) or vector(0)",
     "legendFormat": "Average size"
    },
    {
     "expr": "max(onion_service_descriptor_outer_wrapper_size_bytes) or vector(0)",
     "legendFormat": "Maximum size"
    }
   ]
  },
  {
   "title": "Second layer",
   "type": "timeseries",
   "description": "Minimum, average an maximum second layer descriptor size in bytes (decrypted)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "min(onion_service_descriptor_second_layer_size_bytes) or vector(0)",
     "legendFormat": "Miminum size"
    },
    {
     "expr": "avg(onion_service_descriptor_second_layer_size_bytes) or vector(0)",
     "legendFormat": "Average size"
    },
    {
     "expr": "max(onion_service_descriptor_second_layer_size_bytes) or vector(0)",
     "legendFormat": "Maximum size"
    }
   ]
  },
  { "title": "Introduction points", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Introduction points",
   "type": "timeseries",
   "description": "Minimum, average and maximum introduction points number",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "min(avg_over_time(onion_service_introduction_points_number[30m])) or vector(0)",
     "legendFormat": "Minimum # of intro points"
    },
    {
     "expr": "avg(avg_over_time(onion_service_introduction_points_number[30m])) or vector(0)",
     "legendFormat": "Average # of intro points"
    },
    {
     "expr": "max(avg_over_time(onion_service_introduction_points_number[30m])) or vector(0)",
     "legendFormat": "Max # of intro points"
    }
   ]
  },
  {
   "title": "Number of introduction points",
   "type": "table",
   "description": "Minimum, average and maximum introduction points number",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "targets": [
    {
     "expr": "sort_desc(onion_service_introduction_points_number)"
    }
   ]
  },
  { "title": "HSDirs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "HSDirs tested",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(hsdir_latency_seconds)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HSDir latency",
   "type": "timeseries",
   "description": "HSDir minimum, average and maximum latencies in seconds when fetching descriptors. Each HSDir latency is averaged over a 30 minutes interval.",
   "gridPos": { "h": 8, "w": 9, "x": 4, "y": 80 },
   "targets": [
    {
     "expr": "min(avg_over_time(hsdir_latency_seconds[30m])) or vector(0)",
     "legendFormat": "Minimum latency"
    },
    {
     "expr": "avg(avg_over_time(hsdir_latency_seconds[30m])) or vector(0)",
     "legendFormat": "Average latency"
    },
    {
     "expr": "max(avg_over_time(hsdir_latency_seconds[30m])) or vector(0)",
     "legendFormat": "Maximum latency"
    }
   ]
  },
  {
   "title": "HSDir latency",
   "type": "table",
   "description": "HSDir latency in seconds when fetching descriptors. Each HSDir latency is averaged over a 30 minutes interval.",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 80 },
   "targets": [
    {
     "expr": "sort_desc(avg_over_time(hsdir_latency_seconds[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Proof of Work", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "PoW ratio",
   "type": "gauge",
   "description": "Percentage of Onion Services with PoW currently enabled",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(onion_service_pow_enabled == 1) / count(onion_service_pow_enabled) * 100) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PoW enabled",
   "type": "stat",
   "description": "Current total number of Onion Services with Proof of Work (PoW) enabled",
   "gridPos": { "h": 8, "w": 3, "x": 5, "y": 89 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(onion_service_pow_enabled == 1) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PoW v1 effort",
   "type": "timeseries",
   "description": "Mininum, average and maximum effort for the PoW v1 scheme as seem in all monitored Onion Services",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 89 },
   "targets": [
    {
     "expr": "min(onion_service_pow_v1_effort) or vector(0)",
     "legendFormat": "Minimum effort"
    },
    {
     "expr": "avg(onion_service_pow_v1_effort) or vector(0)",
     "legendFormat": "Average effort"
    },
    {
     "expr": "max(onion_service_pow_v1_effort) or vector(0)",
     "legendFormat": "Maximum effort"
    }
   ]
  },
  {
   "title": "PoW enabled",
   "type": "table",
   "description": "Onion Services with PoW enabled",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "targets": [
    { "expr": "onion_service_pow_enabled == 1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "PoW v1 effort",
   "type": "table",
   "description": "Onion Services with PoW v1 enabled and with effort greater than zero",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "targets": [
    {
     "expr": "onion_service_pow_v1_effort > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}